.\"                                      Hey, EMACS: -*- nroff -*-
.TH SRT-FFPLAY 1 "2022-02-28"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
srt-ffplay \- live transmit a URL via SRT and ffplay
.SH SYNOPSIS
.B srt-ffplay
.RB <
.IR source-URL
.RB >
.SH DESCRIPTION
str-ffplay will call srt-live-transmit to transmit the source URL to
ffplay.
.P
This is mostly used as a testbed for SRT.
.SH SEE ALSO
.BR srt-live-transmit (1),
.BR ffplay (1)
.SH AUTHOR
.PP
This manual page was written by Florian Ernst <florian@debian.org>,
for the Debian project (and may be used by others).
